# Generated by Django 4.2.5 on 2024-02-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employerLogin',
            new_name='employeeLogin',
        ),
    ]
