# Generated by Django 4.2.5 on 2024-02-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
