# Generated by Django 4.2.5 on 2024-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_created_data_login_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('doj', models.CharField(max_length=20)),
                ('created_time', models.TimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
