# Generated by Django 4.2.5 on 2024-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
