# Generated by Django 4.2.5 on 2024-02-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_brief', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('priority', models.CharField(max_length=20)),
                ('attach_file', models.FileField(upload_to='')),
                ('created_time', models.TimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
