# Generated by Django 4.2.5 on 2024-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
