# Generated by Django 4.2.5 on 2024-02-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='portal_image'),
        ),
    ]
