# Generated by Django 4.2.5 on 2024-02-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_manager_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_picture',
            field=models.ImageField(upload_to='portal_image'),
        ),
    ]
