# Generated by Django 4.2.5 on 2024-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_task_task_name_alter_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='portal_image'),
            preserve_default=False,
        ),
    ]
